const generalQuestions = {
  en: [
    {
      type: "question",
      text: "What is the capital of the Philippines?",
      options: ["Cebu", "Davao", "Manila"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "How many days are in one week?",
      options: ["5", "7", "10"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which planet do we live on?",
      options: ["Mars", "Earth", "Venus"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Where does the sun rise?",
      options: ["East", "West", "North"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "How many hours are in one day?",
      options: ["12", "24", "48"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What do we call water when it freezes?",
      options: ["Ice", "Smoke", "Fog"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What month is Christmas celebrated?",
      options: ["October", "November", "December"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "How many planets are in the solar system?",
      options: ["8", "9", "10"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What color do you get when you mix blue and yellow?",
      options: ["Green", "Orange", "Purple"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which body part is used for hearing?",
      options: ["Eyes", "Ears", "Nose"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which gas do we need to breathe?",
      options: ["Oxygen", "Helium", "Smoke"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is the biggest ocean in the world?",
      options: ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "How many minutes are in one hour?",
      options: ["30", "60", "90"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What do you usually look at to check the time?",
      options: ["Clock", "Plate", "Bag"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What do you call a baby chicken?",
      options: ["Duckling", "Chick", "Puppy"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which animal is called the king of the jungle?",
      options: ["Lion", "Horse", "Dog"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
  ],
  tl: [
    {
      type: "question",
      text: "Ano ang capital ng Pilipinas?",
      options: ["Cebu", "Davao", "Manila"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ilang araw ang nasa isang linggo?",
      options: ["5", "7", "10"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong planet ang tinitirhan natin?",
      options: ["Mars", "Earth", "Venus"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Saan sumisikat ang araw?",
      options: ["East", "West", "North"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ilang oras ang nasa isang araw?",
      options: ["12", "24", "48"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang tawag sa tubig kapag nagyelo?",
      options: ["Yelo", "Usok", "Hamog"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong buwan ang Pasko?",
      options: ["October", "November", "December"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ilang planet ang meron sa solar system?",
      options: ["8", "9", "10"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong color ang makukuha kapag pinagsama ang blue at yellow?",
      options: ["Green", "Orange", "Purple"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong part ng katawan ang gamit sa pakikinig?",
      options: ["Mata", "Tenga", "Ilong"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong gas ang kailangan natin para makahinga?",
      options: ["Oxygen", "Helium", "Usok"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang biggest ocean sa mundo?",
      options: ["Indian Ocean", "Pacific Ocean", "Atlantic Ocean"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ilang minuto ang nasa isang oras?",
      options: ["30", "60", "90"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong gamit ang tinitingnan para malaman ang oras?",
      options: ["Relo", "Plato", "Bag"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang tawag sa baby chicken?",
      options: ["Bibe", "Sisiw", "Tuta"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong hayop ang tinatawag na king of the jungle?",
      options: ["Lion", "Horse", "Dog"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
  ],
};

export default generalQuestions;
