const mathQuestions = {
  en: [
    {
      type: "question",
      text: "What is 8 + 7?",
      options: ["15", "14", "16"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is 36 / 6?",
      options: ["5", "6", "7"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is 9 x 4?",
      options: ["32", "36", "40"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is 90 - 38?",
      options: ["52", "48", "58"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is half of 50?",
      options: ["20", "25", "30"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which is bigger?",
      options: ["1/4", "1/8", "1/2"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is 125 + 75?",
      options: ["150", "200", "225"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is 45 / 5?",
      options: ["8", "9", "10"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which shape has 3 sides?",
      options: ["Square", "Circle", "Triangle"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is 7 x 8?",
      options: ["54", "56", "58"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is 1000 - 450?",
      options: ["550", "500", "600"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "How many minutes are in 2 hours?",
      options: ["120", "100", "90"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which of these is an even number?",
      options: ["13", "18", "21"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "How many corners does a square have?",
      options: ["3", "4", "5"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which fraction is equal to 0.75?",
      options: ["1/2", "3/4", "2/5"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is 15 + 15 + 15?",
      options: ["30", "40", "45"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
  ],
  tl: [
    {
      type: "question",
      text: "Ano ang 8 + 7?",
      options: ["15", "14", "16"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang 36 / 6?",
      options: ["5", "6", "7"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang 9 x 4?",
      options: ["32", "36", "40"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang 90 - 38?",
      options: ["52", "48", "58"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang kalahati ng 50?",
      options: ["20", "25", "30"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Alin ang mas malaki?",
      options: ["1/4", "1/8", "1/2"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang 125 + 75?",
      options: ["150", "200", "225"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang 45 / 5?",
      options: ["8", "9", "10"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong shape ang may 3 sides?",
      options: ["Square", "Circle", "Triangle"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang 7 x 8?",
      options: ["54", "56", "58"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang 1000 - 450?",
      options: ["550", "500", "600"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ilang minuto ang nasa 2 hours?",
      options: ["120", "100", "90"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Alin dito ang even number?",
      options: ["13", "18", "21"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ilang corners ang meron sa square?",
      options: ["3", "4", "5"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Aling fraction ang katumbas ng 0.75?",
      options: ["1/2", "3/4", "2/5"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang 15 + 15 + 15?",
      options: ["30", "40", "45"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
  ],
};

export default mathQuestions;
