const scienceQuestions = {
  en: [
    {
      type: "question",
      text: "Which part of a plant absorbs water from the soil?",
      options: ["Roots", "Flowers", "Leaves"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What does a plant need to make food?",
      options: ["Sunlight", "Rocks", "Ink"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which planet is known as the red planet?",
      options: ["Venus", "Mars", "Jupiter"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What do we call the steam from boiling water?",
      options: ["Fog", "Ice", "Steam"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which body part pumps blood?",
      options: ["Heart", "Kidney", "Liver"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which animal lays eggs?",
      options: ["Cat", "Chicken", "Dog"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What do we call the colorful arc in the sky after rain?",
      options: ["Lightning", "Rainbow", "Star"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is the closest star to Earth?",
      options: ["Moon", "Sun", "Mars"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which state of matter has a fixed shape?",
      options: ["Liquid", "Gas", "Solid"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What do we call Earth's movement around the sun?",
      options: ["Revolution", "Swimming", "Jumping"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which body part is used for tasting?",
      options: ["Tongue", "Hand", "Ear"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What is the main source of light in the morning?",
      options: ["Sun", "Candle", "Light bulb"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which animal starts as a caterpillar and later gets wings?",
      options: ["Frog", "Butterfly", "Fish"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "What do we call water that falls from clouds?",
      options: ["Fog", "Rain", "Steam"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which body part helps us breathe?",
      options: ["Lungs", "Knee", "Teeth"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Which animal breathes using gills?",
      options: ["Bird", "Horse", "Fish"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
  ],
  tl: [
    {
      type: "question",
      text: "Anong part ng halaman ang sumisipsip ng tubig sa lupa?",
      options: ["Ugat", "Bulaklak", "Dahon"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang kailangan ng halaman para makagawa ng food?",
      options: ["Sunlight", "Bato", "Tinta"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong planet ang kilala bilang red planet?",
      options: ["Venus", "Mars", "Jupiter"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang tawag sa steam mula sa kumukulong tubig?",
      options: ["Hamog", "Yelo", "Singaw"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong part ng katawan ang nagbobomba ng dugo?",
      options: ["Puso", "Bato", "Atay"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Aling hayop ang nangingitlog?",
      options: ["Pusa", "Manok", "Aso"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang tawag sa makulay na guhit sa langit pagkatapos ng ulan?",
      options: ["Kidlat", "Bahaghari", "Bituin"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang pinakamalapit na bituin sa Earth?",
      options: ["Buwan", "Araw", "Mars"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Aling state of matter ang may fixed na shape?",
      options: ["Liquid", "Gas", "Solid"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang tawag sa pag-ikot ng Earth sa Araw?",
      options: ["Revolution", "Paglangoy", "Pagtalon"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong part ng katawan ang gamit sa panlasa?",
      options: ["Dila", "Kamay", "Tenga"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Alin dito ang pangunahing source of light sa umaga?",
      options: ["Araw", "Kandila", "Bumbilya"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong hayop ang nagsisimula bilang uod at nagiging may pakpak?",
      options: ["Palaka", "Paruparo", "Isda"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Ano ang tawag sa tubig na bumabagsak mula sa ulap?",
      options: ["Hamog", "Ulan", "Singaw"],
      answerIndex: 1,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Anong part ng katawan ang tumutulong sa paghinga?",
      options: ["Baga", "Tuhod", "Ngipin"],
      answerIndex: 0,
      points: 5,
      penalty: 5,
    },
    {
      type: "question",
      text: "Aling hayop ang humihinga gamit ang hasang?",
      options: ["Ibon", "Kabayo", "Isda"],
      answerIndex: 2,
      points: 5,
      penalty: 5,
    },
  ],
};

export default scienceQuestions;
