const uiText = {
  en: {
    startEyebrow: "Start Here",
    startTitle: "Pick Your Language and Quiz",
    startCopy:
      "Choose a language first, then pick the quiz topic you want to play.",
    playerEyebrow: "Player List",
    playerTitle: "Choose Who Can Play",
    playerCopy:
      "This list comes from the local JSON player database. Only players marked as ready can start a quiz.",
    playerReady: "Can Play",
    playerLocked: "Locked",
    playerNeverPlayed: "No games played yet on this device.",
    playerPlayCount: (count) => `Played ${count} ${count === 1 ? "time" : "times"}`,
    playerLastPlayed: (date) => `Last played: ${date}`,
    playerHighScore: (score) => `High Score: ${score}`,
    activityEyebrow: "Player Activity",
    activityTitle: "Recent Game History",
    activityCopy:
      "This is the local play log saved in this browser. Admin access is required to export or clear it.",
    playedPlayersLabel: "Players Who Played",
    totalGamesLabel: "Total Games",
    exportHistory: "Export History",
    clearHistory: "Clear History",
    adminCodeLabel: "Admin Code",
    adminCodePlaceholder: "Enter admin code",
    adminAccessCopy: "Only the admin can export or clear the game history.",
    adminAccessError: "Incorrect admin code.",
    adminUnlocked: "Admin tools unlocked.",
    unlockAdminTools: "Unlock Tools",
    lockAdminTools: "Lock Tools",
    activityEmpty: "No activity yet.",
    playerHint: "Select a player first to unlock the quizzes below.",
    playerSelected: (name) => `${name} is ready. You can choose any quiz below.`,
    playerEmpty: "No playable players are available yet. Update the local JSON database first.",
    questionChip: (count) => `${count} Questions`,
    treatChip: "2 Treat Cards",
    trickChip: "2 Trick Cards",
    languageLabel: "Language",
    languageHint: "You can switch this before starting a game.",
    languages: {
      en: "English",
      tl: "Tagalog",
    },
    questionSummary: (questionCount, actionCardCount) =>
      `${questionCount} questions + ${actionCardCount} bonus cards = ${questionCount + actionCardCount} total cards`,
    gameTitle: "Mini Trick or Treat",
    subtitle: "Open the cards, answer the questions, and try to get the highest score.",
    playerLabel: "Player",
    playerSummary: (name, group) => (group ? `${name} | ${group}` : name),
    scoreLabel: "Score",
    cardsLeftLabel: "Cards Left",
    playAgain: "Play Again",
    restart: "Restart",
    changeQuiz: "Change Quiz",
    boardComplete: "Board complete.",
    totalCardsLabel: (totalCards) => `${totalCards} total cards.`,
    headingByType: {
      treat: "Treat",
      trick: "Trick",
      question: "Question",
    },
    questionTitle: "Answer to earn points",
    actionTitle: "Open this card",
    continue: "Continue",
    close: "Close",
    open: "Open",
    boardAriaLabel: "Mini game board",
    cardNumber: (id) => `Card ${id}`,
    openCardAria: (id) => `Open card ${id}`,
    usedCardAria: (id, label) => `Card ${id}, ${label}`,
    resultLabels: {
      bonus: "Treat",
      trick: "Trick",
      correct: "Correct",
      wrong: "Wrong",
    },
  },
  tl: {
    startEyebrow: "Magsimula Dito",
    startTitle: "Piliin ang Wika at Quiz",
    startCopy:
      "Pumili muna ng wika, tapos piliin ang quiz topic na gusto mong laruin.",
    playerEyebrow: "Listahan ng Players",
    playerTitle: "Piliin Kung Sino ang Pwedeng Maglaro",
    playerCopy:
      "Galing ito sa local JSON player database. Ang mga player na handa lang ang pwedeng magsimula ng quiz.",
    playerReady: "Pwedeng Maglaro",
    playerLocked: "Naka-lock",
    playerNeverPlayed: "Wala pang larong naitala sa device na ito.",
    playerPlayCount: (count) =>
      `${count} ${count === 1 ? "beses" : "beses"} nang naglaro`,
    playerHighScore: (score) => `Highest Score: ${score}`,
    playerLastPlayed: (date) => `Huling laro: ${date}`,
    activityEyebrow: "Aktibidad ng Players",
    activityTitle: "Kamakailang History ng Laro",
    activityCopy:
      "Ito ang local play log na naka-save sa browser na ito. Kailangan ng admin access para ma-export o ma-clear ito.",
    playedPlayersLabel: "Players na Naglaro",
    totalGamesLabel: "Kabuuang Laro",
    exportHistory: "I-export ang History",
    clearHistory: "Burahin ang History",
    adminCodeLabel: "Admin Code",
    adminCodePlaceholder: "Ilagay ang admin code",
    adminAccessCopy:
      "Admin lang ang pwedeng mag-export o mag-clear ng history ng laro.",
    adminAccessError: "Maling admin code.",
    adminUnlocked: "Naka-unlock ang admin tools.",
    unlockAdminTools: "I-unlock ang Tools",
    lockAdminTools: "I-lock ang Tools",
    activityEmpty: "Wala pang activity.",
    playerHint: "Pumili muna ng player para ma-unlock ang mga quiz sa ibaba.",
    playerSelected: (name) => `${name} ay handa na. Pwede ka nang pumili ng quiz sa ibaba.`,
    playerEmpty:
      "Wala pang playable player. I-update muna ang local JSON database.",
    questionChip: (count) => `${count} Tanong`,
    treatChip: "2 Treat Cards",
    trickChip: "2 Trick Cards",
    languageLabel: "Wika",
    languageHint: "Pwede mo itong palitan bago magsimula ng game.",
    languages: {
      en: "English",
      tl: "Tagalog",
    },
    questionSummary: (questionCount, actionCardCount) =>
      `${questionCount} tanong + ${actionCardCount} bonus cards = ${questionCount + actionCardCount} kabuuang cards`,
    gameTitle: "Mini Trick or Treat",
    subtitle: "Buksan ang mga card, sagutin ang mga tanong, at subukang makuha ang pinakamataas na score.",
    playerLabel: "Player",
    playerSummary: (name, group) => (group ? `${name} | ${group}` : name),
    scoreLabel: "Puntos",
    cardsLeftLabel: "Natitirang Cards",
    playAgain: "Ulitin",
    restart: "Simulan Muli",
    changeQuiz: "Palit Quiz",
    boardComplete: "Tapos na ang board.",
    totalCardsLabel: (totalCards) => `${totalCards} kabuuang cards.`,
    headingByType: {
      treat: "Treat",
      trick: "Trick",
      question: "Tanong",
    },
    questionTitle: "Sagutin para sa puntos",
    actionTitle: "Buksan ang card na ito",
    continue: "Magpatuloy",
    close: "Isara",
    open: "Buksan",
    boardAriaLabel: "Board ng mini game",
    cardNumber: (id) => `Card ${id}`,
    openCardAria: (id) => `Buksan ang card ${id}`,
    usedCardAria: (id, label) => `Card ${id}, ${label}`,
    resultLabels: {
      bonus: "Treat",
      trick: "Trick",
      correct: "Tama",
      wrong: "Mali",
    },
  },
};

const actionCardsByLanguage = {
  en: [
    { type: "treat", text: "You found candy. Plus 10 points.", points: 10 },
    { type: "trick", text: "A ghost card appeared. Minus 5 points.", points: 5 },
    { type: "treat", text: "Bonus chocolate. Plus 15 points.", points: 15 },
    { type: "trick", text: "You got caught in a spider web. Minus 10 points.", points: 10 },
  ],
  tl: [
    { type: "treat", text: "May nakuha kang candy. Plus 10 points.", points: 10 },
    { type: "trick", text: "May ghost card. Minus 5 points.", points: 5 },
    { type: "treat", text: "May bonus chocolate ka. Plus 15 points.", points: 15 },
    { type: "trick", text: "Nadali ka ng spider web. Minus 10 points.", points: 10 },
  ],
};

export { actionCardsByLanguage, uiText };
